
export const products = [
  {
    id: 1,
    name: "Heirloom Silk Charmeuse",
    category: "silk",
    price: 285,
    image: "/NaturalLinenFabric.jpg",
    description: "22 Momme · 114cm Width. A luxurious, high-luster silk with a beautiful drape, perfect for evening wear and lingerie.",
    colors: ["Ivory", "Noir", "Pearl"],
  },
  {
    id: 2,
    name: "Belgian Linen Canvas",
    category: "linen",
    price: 145,
    image: "/fabric1.jpg",
    description: "100% European Flax · 150cm. Durable and breathable, this linen canvas softens with every wash.",
    colors: ["Natural", "Stone", "Ash"],
  },
  {
    id: 3,
    name: "Merino Wool Suiting",
    category: "wool",
    price: 320,
    image: "/SilkCharmeuse.jpg",
    description: "Super 150s · 152cm Width. Exceptionally fine wool for bespoke tailoring.",
    colors: ["Charcoal", "Navy", "Camel"],
  },
  {
    id: 4,
    name: "Habotai Silk Lining",
    category: "silk",
    price: 95,
    image: "/fabric2.jpg",
    description: "8 Momme · 110cm Width. Lightweight and smooth, ideal for lining garments.",
    colors: ["Champagne", "Rose", "Dove"],
  },
  {
    id: 5,
    name: "Irish Linen Shirting",
    category: "linen",
    price: 165,
    image: "/CottonFloralPrint.jpg",
    description: "Pure Linen · 140cm Width. Crisp and cool, the gold standard for summer shirting.",
    colors: ["White", "Ecru", "Sky"],
  },
  {
    id: 6,
    name: "Cashmere Wool Blend",
    category: "wool",
    price: 425,
    image: "/fabric3.jpg",
    description: "80% Wool 20% Cashmere · 148cm. The ultimate in softness and warmth for coatings.",
    colors: ["Taupe", "Burgundy", "Forest"],
  },
  {
    id: 7,
    name: "Egyptian Cotton Poplin",
    category: "cotton",
    price: 125,
    image: "/fabric4.jpg",
    description: "120 Thread Count · 145cm. Smooth, crisp finish perfect for structured garments.",
    colors: ["Bright White", "Cream", "Slate"],
  },
  {
    id: 8,
    name: "Raw Silk Dupioni",
    category: "silk",
    price: 195,
    image: "/MerinoWoolBlend.jpg",
    description: "100% Pure Silk · 112cm Width. Textured silk with characteristic slubs.",
    colors: ["Copper", "Emerald", "Sapphire"],
  },
  {
    id: 9,
    name: "French Linen Voile",
    category: "linen",
    price: 185,
    image: "/fabric5.jpg",
    description: "Sheer Weight · 135cm Width. Delicate and airy, perfect for curtains or summer dresses.",
    colors: ["Powder", "Mist", "Sand"],
  },
];