// lib/data.ts

export const products = [
  {
    id: 1,
    name: "Heirloom Silk Charmeuse",
    category: "silk",
    price: 285,
    image: "https://images.pexels.com/photos/3713212/pexels-photo-3713212.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "22 Momme · 114cm Width. A luxurious, high-luster silk with a beautiful drape, perfect for evening wear and lingerie.",
    colors: ["Ivory", "Noir", "Pearl"],
  },
  {
    id: 2,
    name: "Belgian Linen Canvas",
    category: "linen",
    price: 145,
    image: "https://images.pexels.com/photos/6474471/pexels-photo-6474471.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "100% European Flax · 150cm. Durable and breathable, this linen canvas softens with every wash.",
    colors: ["Natural", "Stone", "Ash"],
  },
  {
    id: 3,
    name: "Merino Wool Suiting",
    category: "wool",
    price: 320,
    image: "https://images.pexels.com/photos/7679682/pexels-photo-7679682.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Super 150s · 152cm Width. Exceptionally fine wool for bespoke tailoring.",
    colors: ["Charcoal", "Navy", "Camel"],
  },
  {
    id: 4,
    name: "Habotai Silk Lining",
    category: "silk",
    price: 95,
    image: "https://images.pexels.com/photos/6474459/pexels-photo-6474459.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "8 Momme · 110cm Width. Lightweight and smooth, ideal for lining garments.",
    colors: ["Champagne", "Rose", "Dove"],
  },
  {
    id: 5,
    name: "Irish Linen Shirting",
    category: "linen",
    price: 165,
    image: "https://images.pexels.com/photos/5699456/pexels-photo-5699456.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Pure Linen · 140cm Width. Crisp and cool, the gold standard for summer shirting.",
    colors: ["White", "Ecru", "Sky"],
  },
  {
    id: 6,
    name: "Cashmere Wool Blend",
    category: "wool",
    price: 425,
    image: "https://images.pexels.com/photos/6474476/pexels-photo-6474476.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "80% Wool 20% Cashmere · 148cm. The ultimate in softness and warmth for coatings.",
    colors: ["Taupe", "Burgundy", "Forest"],
  },
  {
    id: 7,
    name: "Egyptian Cotton Poplin",
    category: "cotton",
    price: 125,
    image: "https://images.pexels.com/photos/5698852/pexels-photo-5698852.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "120 Thread Count · 145cm. Smooth, crisp finish perfect for structured garments.",
    colors: ["Bright White", "Cream", "Slate"],
  },
  {
    id: 8,
    name: "Raw Silk Dupioni",
    category: "silk",
    price: 195,
    image: "https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?q=80&w=1000&auto=format&fit=crop",
    description: "100% Pure Silk · 112cm Width. Textured silk with characteristic slubs.",
    colors: ["Copper", "Emerald", "Sapphire"],
  },
  {
    id: 9,
    name: "French Linen Voile",
    category: "linen",
    price: 185,
    image: "https://images.unsplash.com/photo-1617325247661-675ab4b64ae2?q=80&w=1000&auto=format&fit=crop",
    description: "Sheer Weight · 135cm Width. Delicate and airy, perfect for curtains or summer dresses.",
    colors: ["Powder", "Mist", "Sand"],
  },
];